# -*- coding: utf-8 -*-
"""Simulation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12jcupM2U25ShTX2JUnBt9QaaxLxzabrc

# **Simulation of Smart Grid**

Install and import mosaik
"""

!pip install mosaik

import mosaik

"""Install krangpower (To simulate grid based on OpenDDS)"""

!pip install krangpower

"""Import essential libraries and define units to use the pint library"""

import numpy as np
import numpy.fft as fft
from PIL import Image
import matplotlib.pyplot as plt
import cvxpy as cp  # For optimization

import krangpower as kp  # This is our main library
unit = kp.UM

"""# Start with our grid"""

src = kp.Vsource(basekv=220*unit.V, frequency=100.0) # Make a voltage source with voltage 220 V and frquency 100 Hz

grid = kp.Krang('theGrid', src)  # Instantiate a grid as a krang object (we can have only one of those) with our source above





totalProduction=0
totalConsumption=0

"""## The prosumer class"""

class prosumer(kp.DecisionModel, id):
  def __init__(id, production =, consumption=):
    self.id = id
    self.production = production
    self.consumption = consumption

  def decide_pq(self, oek, mynode):
    hour = oek.brain.Solution.DblHour()  # Extracts which hour the simulation is currently on
    # Optimization by scheduling algo goes here

